In [1]:
import os

In [3]:
os.getcwd()

'c:\\Users\\hp\\OneDrive\\Desktop\\training\\python'

In [6]:
path = r'c:\\Users\\hp\\OneDrive\\Desktop\\training\\python'
os.listdir(path)

['2conditional.ipynb',
 'Assignment 2.ipynb',
 'Assignment.py',
 'condition3.ipynb',
 'conditional.ipynb',
 'numpy.ipynb',
 'Oops.ipynb',
 'python practice.py',
 'python1.py',
 'python2']

In [ ]:
os.mkdir("Demo") #To create a folder


In [15]:
os.remove("C:\Users\hp\OneDrive\Desktop\training\python\Demo")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (118725135.py, line 1)

In [17]:
os.rename("Demo","Basic")

In [23]:
os.chdir(r"C:\Users\hp\OneDrive\Desktop\training\python\Basic")
os.getcwd()

'C:\\Users\\hp\\OneDrive\\Desktop\\training\\python\\Basic'

In [27]:
os.chdir(r"C:\Users\hp\OneDrive\Desktop\training\python")
os.getcwd()

'C:\\Users\\hp\\OneDrive\\Desktop\\training\\python'

In [30]:
pip install numpy

  Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)
print(type(lst))
arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr = list(range(10))
print(arr)
print(type(arr))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [8]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.zeros((6,10)) # 6 = row and 10 = column
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr = np.ones((11,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
arr.dtype

dtype('float64')

In [20]:
arr = np.arange(60.0)

In [22]:
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(60,)
float64
60
1


In [ ]:
arr = arr.reshape(12,5)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54.],
       [55., 56., 57., 58., 59.]])

In [24]:
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(12, 5)
float64
60
2


In [34]:
arr[5:7]
arr


array([[0.]])

In [36]:
arr = np.arange(60)

In [38]:
arr = arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [39]:
arr = arr[0:1,0:1]
arr

array([[0]])

In [58]:
arr[8:10,2:4]

TypeError: list indices must be integers or slices, not tuple

In [67]:
arr = np.arange(225)

In [68]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [69]:
arr=arr.reshape(5,15,3)

In [70]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [71]:
arr



array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [75]:
arr[0:,0:1,0:1]


array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [76]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [81]:
arr[0:1,0:2,0:1,0:2,0:1,0:2] 

IndexError: too many indices for array: array is 3-dimensional, but 6 were indexed

In [79]:
arr.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [80]:
arr.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [82]:
np.random.randint(1,10,5)

array([5, 3, 9, 3, 9], dtype=int32)

In [83]:
np.random.randint(1,10,(5,7))

array([[6, 3, 4, 6, 5, 2, 8],
       [3, 6, 8, 3, 3, 1, 6],
       [7, 7, 4, 4, 3, 4, 7],
       [3, 2, 6, 7, 4, 2, 7],
       [9, 9, 7, 1, 6, 8, 3]], dtype=int32)

In [84]:
np.random.random(10)

array([0.33075102, 0.22789199, 0.11512388, 0.23733581, 0.1765225 ,
       0.09949624, 0.74133457, 0.81145556, 0.77537546, 0.73246947])

In [86]:
np.random.normal(10)

10.190711645643665

In [88]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [95]:
arr1 = np.arr((6,8))
arr2 = np.arr((3,8))


AttributeError: module 'numpy' has no attribute 'arr'

In [96]:
arr*2




array([[[  0,   2,   4],
        [  6,   8,  10],
        [ 12,  14,  16],
        [ 18,  20,  22],
        [ 24,  26,  28],
        [ 30,  32,  34],
        [ 36,  38,  40],
        [ 42,  44,  46],
        [ 48,  50,  52],
        [ 54,  56,  58],
        [ 60,  62,  64],
        [ 66,  68,  70],
        [ 72,  74,  76],
        [ 78,  80,  82],
        [ 84,  86,  88]],

       [[ 90,  92,  94],
        [ 96,  98, 100],
        [102, 104, 106],
        [108, 110, 112],
        [114, 116, 118],
        [120, 122, 124],
        [126, 128, 130],
        [132, 134, 136],
        [138, 140, 142],
        [144, 146, 148],
        [150, 152, 154],
        [156, 158, 160],
        [162, 164, 166],
        [168, 170, 172],
        [174, 176, 178]],

       [[180, 182, 184],
        [186, 188, 190],
        [192, 194, 196],
        [198, 200, 202],
        [204, 206, 208],
        [210, 212, 214],
        [216, 218, 220],
        [222, 224, 226],
        [228, 230, 232],
        [234, 236, 23

# svd

In [ ]:
problem
data cleaning
EDA preprocessing
Encoding
split train Test 
predict-Model

In [99]:
pip install pandas

  Using cached pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
 

In [100]:
import pandas as pd

In [101]:
data = pd.read_csv('C:\Users\hp\OneDrive\Desktop\Used_Bikes.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1351343716.py, line 1)